apiVersion: serving.knative.dev/v1 # Current version of Knative
kind: Service
metadata:
  name: app-java # The name of the app
  namespace: default # The namespace the app will use
spec:
  template:
  
      spec:
      containers:
        - image: docker.io/nitesh2879/my-examplerepo  # The URL to the image of the app
          env:
            - name: TARGET # The environment variable printed out by the sample app
              value: "appdemo Sample v2"